version: '3'

services:
  db:
    image: "postgres:9.6.17-alpine"
    environment:
      POSTGRES_DB: digivox
      POSTGRES_USER: digivox
      POSTGRES_PASSWORD: digivox

  app:
    build: .
    ports:
      - "3001:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db/digivox
      SPRING_DATASOURCE_USERNAME: digivox
      SPRING_DATASOURCE_PASSWORD: digivox
    depends_on:
      - db